### PR TITLE
Resolves issue #3

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Resolves issue #3.

### CODE REVIEW

**Comment by peter279k** [comment]
@mpscholten, it still didn't run the CircleCI build on PR automatically.

IMHO, I think we should consider revoking CircleCI build setting permission.

If possible, I can work on this setting if I'm repository collaborator :smile:.

**Comment by mpscholten** [comment]
Just made you collaborator (I think you need to accept at https://github.com/mpscholten/typesafe-enum/invitations) :) Feel free to change build settings on Circle.

**Comment by peter279k** [comment]
@mpscholten, thanks for your quick invitation.

Actually, I still don't have the permission to revoke Circle CI setting on this repository.

You may revoke setting via CirCle build repository setting page.

image

**Comment by mpscholten** [comment]
Just tried to revoke the Circle CI settings, but haven't found a way. Any ideas where I can find this options? For the last PR the build actually went through, see https://circleci.com/gh/mpscholten/typesafe-enum/8#tests/containers/0. So maybe this was just aa issue on Circle CI's side?

Also feel free to merge incoming PR's when they're good to merge. Happy to have you onboard as a co-maintainer :)

**Comment by peter279k** [comment]
Hi @mpscholten, thanks for your reply.

Never mind. Just check the CI build log on Circle CI page at this moment :).

**Pull request merged**
